
import React, { useState } from 'react';
import { User, ServiceStatus, Transaction, ChatMessage, AppSettings, Offer } from '../types';
import { Users, CheckCircle, XCircle, Clock, Smartphone, LogOut, Settings, Edit3, Image, CreditCard, Plus, Trash2, Tag, ChevronRight, Send, Lock, User as UserIcon, Database, Copy, AlertTriangle } from 'lucide-react';
import { ExtendedChatMessage } from '../App';
import { OPERATORS } from '../constants';
import { useNavigate } from 'react-router-dom';

interface Props {
  user: User;
  users: User[];
  services: ServiceStatus[];
  settings: AppSettings;
  offers: Offer[];
  onManageOffers: (action: 'ADD' | 'DELETE', offer?: Offer) => void;
  onUpdateSettings: (s: Partial<AppSettings>) => void;
  onUpdateUser: (id: string, data: Partial<User>) => void;
  onToggleService: (id: string) => void;
  onLogout: () => void;
  transactions: Transaction[];
  onUpdateTransaction: (txId: string, status: 'SUCCESS' | 'FAILED') => void;
  chatMessages: ExtendedChatMessage[];
  onAdminReply: (text: string, isAdmin: boolean, recipientId?: string) => void;
}

const AdminDashboard: React.FC<Props> = ({ user, users, services, settings, offers, onManageOffers, onUpdateSettings, onUpdateUser, onToggleService, onLogout, transactions, onUpdateTransaction, chatMessages, onAdminReply }) => {
  const [activeTab, setActiveTab] = useState<'STATS' | 'REQUESTS' | 'USERS' | 'OFFERS' | 'CHAT' | 'DATABASE' | 'SETTINGS'>('STATS');
  const navigate = useNavigate();
  
  // Full Case-Sensitive SQL to initialize everything correctly
  const fullSqlSetup = `-- 1. Users Table Fix (CamelCase Columns Quoted)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  "password" TEXT,
  role TEXT DEFAULT 'USER',
  balance NUMERIC DEFAULT 0,
  "driveBalance" NUMERIC DEFAULT 0,
  "isBlocked" BOOLEAN DEFAULT false
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS "password" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "driveBalance" NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "isBlocked" BOOLEAN DEFAULT false;

-- 2. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" TEXT NOT NULL,
  type TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'PENDING',
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  details TEXT,
  operator TEXT
);

-- 3. Offers Table
CREATE TABLE IF NOT EXISTS offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL,
  "regularPrice" NUMERIC,
  operator TEXT,
  validity TEXT,
  description TEXT
);

-- 4. Chat Messages Table
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "senderId" TEXT NOT NULL,
  "recipientId" TEXT,
  text TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  "isAdmin" BOOLEAN DEFAULT false
);

-- 5. App Settings Table
CREATE TABLE IF NOT EXISTS app_settings (
  id INT PRIMARY KEY,
  "bkashNumber" TEXT,
  "nagadNumber" TEXT,
  "rocketNumber" TEXT,
  banners TEXT[]
);

INSERT INTO app_settings (id, "bkashNumber", "nagadNumber", "rocketNumber", "banners")
VALUES (1, '01XXXXXXXXX', '01XXXXXXXXX', '01XXXXXXXXX', ARRAY[]::TEXT[])
ON CONFLICT (id) DO NOTHING;`;

  const copySql = () => {
    navigator.clipboard.writeText(fullSqlSetup);
    alert("SQL কপি হয়েছে! সুপাবেজে রান করুন।");
  };

  const pendingTransactions = transactions.filter(t => t.status === 'PENDING');

  return (
    <div className="flex-1 flex flex-col bg-gray-50 overflow-hidden h-full">
      <header className="bg-white border-b p-4 flex justify-between items-center sticky top-0 z-10 shadow-sm">
        <div className="flex items-center space-x-2">
          <div className="w-8 h-8 bg-blue-900 rounded-lg flex items-center justify-center text-white">
            <Settings size={18} />
          </div>
          <h1 className="text-lg font-black text-gray-800 tracking-tight">অ্যাডমিন প্যানেল</h1>
        </div>
        <button onClick={onLogout} className="p-2 bg-red-50 text-red-500 rounded-xl active:scale-95 transition-all">
          <LogOut size={20} />
        </button>
      </header>

      <div className="bg-white flex border-b overflow-x-auto no-scrollbar scroll-smooth">
        {[
          { id: 'STATS', label: 'Stats', icon: <Smartphone size={14}/> },
          { id: 'REQUESTS', label: `Req (${pendingTransactions.length})`, icon: <Clock size={14}/> },
          { id: 'USERS', label: 'Users', icon: <Users size={14}/> },
          { id: 'OFFERS', label: 'Offers', icon: <Tag size={14}/> },
          { id: 'CHAT', label: 'Live Chat', icon: <Send size={14}/> },
          { id: 'DATABASE', label: 'Database Fix', icon: <Database size={14}/> },
          { id: 'SETTINGS', label: 'Settings', icon: <Settings size={14}/> },
        ].map((tab) => (
          <button 
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={`flex items-center space-x-2 whitespace-nowrap px-6 py-4 text-[10px] font-black uppercase tracking-widest transition-all ${activeTab === tab.id ? 'text-blue-900 border-b-4 border-blue-900 bg-blue-50/50' : 'text-gray-400 hover:text-gray-600'}`}
          >
            {tab.icon}
            <span>{tab.label}</span>
          </button>
        ))}
      </div>

      <div className="flex-1 overflow-y-auto pb-20 bg-gray-50/50">
        {activeTab === 'STATS' && (
          <div className="p-6 grid grid-cols-2 gap-4">
             <div className="bg-gradient-to-br from-blue-600 to-blue-800 p-6 rounded-[32px] text-white shadow-xl">
                <p className="text-[10px] font-bold opacity-70 uppercase mb-1">মোট ইউজার</p>
                <p className="text-3xl font-black">{users.length}</p>
             </div>
             <div className="bg-gradient-to-br from-orange-500 to-red-600 p-6 rounded-[32px] text-white shadow-xl">
                <p className="text-[10px] font-bold opacity-70 uppercase mb-1">পেন্ডিং অনুরোধ</p>
                <p className="text-3xl font-black">{pendingTransactions.length}</p>
             </div>
          </div>
        )}

        {activeTab === 'DATABASE' && (
          <div className="p-6">
             <div className="bg-white p-8 rounded-[40px] shadow-xl border border-blue-100">
                <div className="flex items-center space-x-4 mb-6">
                   <div className="w-14 h-14 bg-red-100 rounded-2xl flex items-center justify-center text-red-600">
                      <AlertTriangle size={30} />
                   </div>
                   <div>
                      <h3 className="text-xl font-black text-gray-800 tracking-tight">সিস্টেম ডেটাবেস মেরামত</h3>
                      <p className="text-gray-500 text-[10px] font-bold uppercase tracking-widest">Database Schema Fixer</p>
                   </div>
                </div>

                <div className="bg-amber-50 border-l-4 border-amber-400 p-5 mb-8 rounded-r-2xl">
                   <p className="text-amber-800 text-xs font-bold leading-relaxed">
                     আপনার সুপাবেজে 'password' কলামটি নেই। নিচের SQL কোডটি কপি করে সুপাবেজের **SQL Editor** এ রান করুন। এতে সব সমস্যা ঠিক হয়ে যাবে।
                   </p>
                </div>
                
                <div className="bg-gray-900 p-6 rounded-3xl relative mb-8 group border-4 border-gray-800 shadow-inner overflow-hidden">
                   <pre className="max-h-60 overflow-y-auto no-scrollbar font-mono text-[9px] text-emerald-400 leading-relaxed">
                      {fullSqlSetup}
                   </pre>
                   <div className="absolute top-4 right-4 bg-gray-800 p-2 rounded-xl text-white group-hover:bg-blue-600 transition-colors pointer-events-none">
                      <Copy size={16} />
                   </div>
                </div>

                <button 
                  onClick={copySql}
                  className="w-full bg-blue-900 text-white py-5 rounded-2xl font-black text-sm uppercase tracking-widest shadow-2xl flex items-center justify-center gap-3 active:scale-95 transition-all mb-4"
                >
                  <Copy size={20} /> SQL কোড কপি করুন
                </button>

                <div className="mt-8 text-center p-4 bg-gray-50 rounded-2xl">
                   <p className="text-[10px] text-gray-400 font-bold uppercase mb-2">কোডটি কোথায় রান করবেন?</p>
                   <a 
                    href="https://supabase.com/dashboard/project/sxigiychhjxwisxbaamh/sql/new" 
                    target="_blank" 
                    rel="noreferrer"
                    className="text-blue-600 font-black text-xs underline underline-offset-4"
                   >
                    সরাসরি সুপাবেজ SQL এডিটরে যান →
                   </a>
                </div>
             </div>
          </div>
        )}

        {activeTab === 'REQUESTS' && (
          <div className="p-4 space-y-4">
             {pendingTransactions.length === 0 ? (
               <div className="text-center py-20 text-gray-300 font-black uppercase tracking-widest text-[10px]">পেন্ডিং কোনো অনুরোধ নেই</div>
             ) : (
               pendingTransactions.map(tx => (
                 <div key={tx.id} className="bg-white p-6 rounded-[32px] border shadow-sm space-y-4">
                    <div className="flex justify-between items-start">
                       <div>
                          <p className="text-[10px] font-black text-blue-900 uppercase bg-blue-50 px-2 py-1 rounded-lg inline-block mb-2">{tx.type}</p>
                          <p className="text-xl font-black text-gray-800">৳ {tx.amount}</p>
                       </div>
                       <p className="text-[10px] text-gray-400 font-bold">{new Date(tx.date).toLocaleString()}</p>
                    </div>
                    <div className="bg-gray-50 p-4 rounded-2xl">
                       <p className="text-xs font-bold text-gray-600">বিস্তারিত: {tx.details}</p>
                    </div>
                    <div className="flex space-x-3">
                       <button onClick={() => onUpdateTransaction(tx.id, 'SUCCESS')} className="flex-1 bg-green-500 text-white py-3 rounded-xl font-black text-xs uppercase shadow-lg shadow-green-200">Approve</button>
                       <button onClick={() => onUpdateTransaction(tx.id, 'FAILED')} className="flex-1 bg-red-500 text-white py-3 rounded-xl font-black text-xs uppercase shadow-lg shadow-red-200">Reject</button>
                    </div>
                 </div>
               ))
             )}
          </div>
        )}

        {activeTab === 'USERS' && (
           <div className="p-4 space-y-3">
              {users.map(u => (
                <div key={u.id} className="bg-white p-4 rounded-2xl border flex items-center justify-between">
                   <div className="flex items-center space-x-3">
                      <div className="w-10 h-10 rounded-full bg-gray-100 flex items-center justify-center">
                        <UserIcon size={18} className="text-gray-400" />
                      </div>
                      <div>
                         <p className="text-sm font-black text-gray-800">{u.name}</p>
                         <p className="text-[10px] text-gray-400 font-bold">{u.phone}</p>
                      </div>
                   </div>
                   <div className="text-right">
                      <p className="text-sm font-black text-blue-900">৳ {u.balance}</p>
                      <p className="text-[9px] font-bold text-gray-400 uppercase">{u.role}</p>
                   </div>
                </div>
              ))}
           </div>
        )}
      </div>
    </div>
  );
};

export default AdminDashboard;
