
import React, { useState } from 'react';
import { User, ServiceStatus, Transaction, ChatMessage, AppSettings, Offer } from '../types';
import { Users, CheckCircle, XCircle, Clock, Smartphone, LogOut, Settings, Edit3, Image, CreditCard, Plus, Trash2, Tag, ChevronRight, Send, Lock, User as UserIcon, Database, Copy, AlertTriangle } from 'lucide-react';
import { ExtendedChatMessage } from '../App';
import { OPERATORS } from '../constants';
import { useNavigate } from 'react-router-dom';

interface Props {
  user: User;
  users: User[];
  services: ServiceStatus[];
  settings: AppSettings;
  offers: Offer[];
  onManageOffers: (action: 'ADD' | 'DELETE', offer?: Offer) => void;
  onUpdateSettings: (s: Partial<AppSettings>) => void;
  onUpdateUser: (id: string, data: Partial<User>) => void;
  onToggleService: (id: string) => void;
  onLogout: () => void;
  transactions: Transaction[];
  onUpdateTransaction: (txId: string, status: 'SUCCESS' | 'FAILED') => void;
  chatMessages: ExtendedChatMessage[];
  onAdminReply: (text: string, isAdmin: boolean, recipientId?: string) => void;
}

const AdminDashboard: React.FC<Props> = ({ user, users, services, settings, offers, onManageOffers, onUpdateSettings, onUpdateUser, onToggleService, onLogout, transactions, onUpdateTransaction, chatMessages, onAdminReply }) => {
  const [activeTab, setActiveTab] = useState<'STATS' | 'REQUESTS' | 'USERS' | 'OFFERS' | 'CHAT' | 'DATABASE' | 'SETTINGS'>('STATS');
  
  // Full SQL Fix Script
  const fullSqlSetup = `-- ১. ইউজার টেবিল মেরামত
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  "password" TEXT,
  "payPassword" TEXT,
  role TEXT DEFAULT 'USER',
  balance NUMERIC DEFAULT 0,
  "driveBalance" NUMERIC DEFAULT 0,
  "isBlocked" BOOLEAN DEFAULT false
);

ALTER TABLE users ALTER COLUMN id TYPE TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "password" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "payPassword" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'USER';
ALTER TABLE users ADD COLUMN IF NOT EXISTS "balance" NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "driveBalance" NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "isBlocked" BOOLEAN DEFAULT false;

-- ২. ট্রানজেকশন টেবিল
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" TEXT NOT NULL,
  type TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'PENDING',
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  details TEXT,
  operator TEXT
);

-- ৩. অফার টেবিল
CREATE TABLE IF NOT EXISTS offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL,
  "regularPrice" NUMERIC,
  operator TEXT,
  validity TEXT,
  description TEXT
);

-- ৪. চ্যাট টেবিল
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "senderId" TEXT NOT NULL,
  "recipientId" TEXT,
  text TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  "isAdmin" BOOLEAN DEFAULT false
);

-- ৫. সেটিংস টেবিল
CREATE TABLE IF NOT EXISTS app_settings (
  id INT PRIMARY KEY,
  "bkashNumber" TEXT,
  "nagadNumber" TEXT,
  "rocketNumber" TEXT,
  banners TEXT[]
);

INSERT INTO app_settings (id, "bkashNumber", "nagadNumber", "rocketNumber", "banners")
VALUES (1, '01XXXXXXXXX', '01XXXXXXXXX', '01XXXXXXXXX', ARRAY[]::TEXT[])
ON CONFLICT (id) DO NOTHING;

-- ৬. ক্যাশ রিলোড (মোস্ট ইম্পর্ট্যান্ট)
NOTIFY pgrst, 'reload schema';`;

  const copySql = () => {
    navigator.clipboard.writeText(fullSqlSetup);
    alert("Full SQL কপি হয়েছে! সুপাবেজে রান করুন।");
  };

  const pendingTransactions = transactions.filter(t => t.status === 'PENDING');

  return (
    <div className="flex-1 flex flex-col bg-gray-50 overflow-hidden h-full">
      <header className="bg-white border-b p-4 flex justify-between items-center sticky top-0 z-10 shadow-sm">
        <div className="flex items-center space-x-2">
          <div className="w-8 h-8 bg-blue-900 rounded-lg flex items-center justify-center text-white">
            <Settings size={18} />
          </div>
          <h1 className="text-lg font-black text-gray-800 tracking-tight">অ্যাডমিন প্যানেল</h1>
        </div>
        <button onClick={onLogout} className="p-2 bg-red-50 text-red-500 rounded-xl active:scale-95 transition-all">
          <LogOut size={20} />
        </button>
      </header>

      <div className="bg-white flex border-b overflow-x-auto no-scrollbar scroll-smooth">
        {[
          { id: 'STATS', label: 'Stats', icon: <Smartphone size={14}/> },
          { id: 'REQUESTS', label: `Req (${pendingTransactions.length})`, icon: <Clock size={14}/> },
          { id: 'USERS', label: 'Users', icon: <Users size={14}/> },
          { id: 'OFFERS', label: 'Offers', icon: <Tag size={14}/> },
          { id: 'CHAT', label: 'Live Chat', icon: <Send size={14}/> },
          { id: 'DATABASE', label: 'Database Fix', icon: <Database size={14}/> },
          { id: 'SETTINGS', label: 'Settings', icon: <Settings size={14}/> },
        ].map((tab) => (
          <button 
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={`flex items-center space-x-2 whitespace-nowrap px-6 py-4 text-[10px] font-black uppercase tracking-widest transition-all ${activeTab === tab.id ? 'text-blue-900 border-b-4 border-blue-900 bg-blue-50/50' : 'text-gray-400 hover:text-gray-600'}`}
          >
            {tab.icon}
            <span>{tab.label}</span>
          </button>
        ))}
      </div>

      <div className="flex-1 overflow-y-auto pb-20 bg-gray-50/50">
        {activeTab === 'DATABASE' && (
          <div className="p-6">
             <div className="bg-white p-8 rounded-[40px] shadow-xl border border-blue-100">
                <div className="flex items-center space-x-4 mb-6">
                   <div className="w-14 h-14 bg-red-100 rounded-2xl flex items-center justify-center text-red-600 shadow-inner">
                      <AlertTriangle size={30} />
                   </div>
                   <div>
                      <h3 className="text-xl font-black text-gray-800 tracking-tight">সিস্টেম মেরামত</h3>
                      <p className="text-gray-500 text-[10px] font-bold uppercase tracking-widest">Database Schema Fixer</p>
                   </div>
                </div>

                <div className="bg-amber-50 border-l-4 border-amber-400 p-5 mb-8 rounded-r-2xl">
                   <p className="text-amber-900 text-xs font-bold leading-relaxed">
                     আপনার রেজিস্ট্রেশনে <b>'payPassword'</b> এরর আসার অর্থ হলো কলামটি আপনার ডাটাবেসে নেই। নিচের কোডটি কপি করে সুপাবেজে রান করুন। এটি <b>ID</b> কলামকেও ঠিক করে দেবে।
                   </p>
                </div>
                
                <div className="bg-gray-900 p-6 rounded-3xl relative mb-8 group border-4 border-gray-800 shadow-inner overflow-hidden">
                   <pre className="max-h-60 overflow-y-auto no-scrollbar font-mono text-[9px] text-emerald-400 leading-relaxed">
                      {fullSqlSetup}
                   </pre>
                   <div className="absolute top-4 right-4 bg-gray-800 p-2 rounded-xl text-white group-hover:bg-blue-600 transition-colors pointer-events-none">
                      <Copy size={16} />
                   </div>
                </div>

                <button 
                  onClick={copySql}
                  className="w-full bg-blue-900 text-white py-5 rounded-2xl font-black text-sm uppercase tracking-widest shadow-2xl flex items-center justify-center gap-3 active:scale-95 transition-all mb-4"
                >
                  <Copy size={20} /> সম্পূর্ণ SQL কপি করুন
                </button>
             </div>
          </div>
        )}

        {activeTab === 'STATS' && (
          <div className="p-6 grid grid-cols-2 gap-4">
             <div className="bg-gradient-to-br from-blue-600 to-blue-800 p-6 rounded-[32px] text-white shadow-xl">
                <p className="text-[10px] font-bold opacity-70 uppercase mb-1">মোট ইউজার</p>
                <p className="text-3xl font-black">{users.length}</p>
             </div>
             <div className="bg-gradient-to-br from-orange-500 to-red-600 p-6 rounded-[32px] text-white shadow-xl">
                <p className="text-[10px] font-bold opacity-70 uppercase mb-1">পেন্ডিং অনুরোধ</p>
                <p className="text-3xl font-black">{pendingTransactions.length}</p>
             </div>
          </div>
        )}
        
        {/* Previous tabs logic... */}
      </div>
    </div>
  );
};

export default AdminDashboard;
