
import React, { useState } from 'react';
import { User, ServiceStatus, Transaction, ChatMessage, AppSettings, Offer } from '../types';
import { Users, CheckCircle, XCircle, Clock, Smartphone, LogOut, Settings, Edit3, Image, CreditCard, Plus, Trash2, Tag, ChevronRight, Send, Lock, User as UserIcon, Database, Copy, AlertTriangle } from 'lucide-react';
import { ExtendedChatMessage } from '../App';
import { OPERATORS } from '../constants';
import { useNavigate } from 'react-router-dom';

interface Props {
  user: User;
  users: User[];
  services: ServiceStatus[];
  settings: AppSettings;
  offers: Offer[];
  onManageOffers: (action: 'ADD' | 'DELETE', offer?: Offer) => void;
  onUpdateSettings: (s: Partial<AppSettings>) => void;
  onUpdateUser: (id: string, data: Partial<User>) => void;
  onToggleService: (id: string) => void;
  onLogout: () => void;
  transactions: Transaction[];
  onUpdateTransaction: (txId: string, status: 'SUCCESS' | 'FAILED') => void;
  chatMessages: ExtendedChatMessage[];
  onAdminReply: (text: string, isAdmin: boolean, recipientId?: string) => void;
}

const AdminDashboard: React.FC<Props> = ({ user, users, services, settings, offers, onManageOffers, onUpdateSettings, onUpdateUser, onToggleService, onLogout, transactions, onUpdateTransaction, chatMessages, onAdminReply }) => {
  const [activeTab, setActiveTab] = useState<'STATS' | 'REQUESTS' | 'USERS' | 'OFFERS' | 'CHAT' | 'DATABASE' | 'SETTINGS'>('STATS');
  
  const fullSqlReset = `-- ১. সম্পূর্ণ রিসেট (সতর্কতা: এটি সব ডাটা মুছে দিবে)
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS offers CASCADE;
DROP TABLE IF EXISTS app_settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ২. ইউজার টেবিল
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "payPassword" TEXT NOT NULL,
  role TEXT DEFAULT 'USER',
  balance NUMERIC DEFAULT 0,
  "driveBalance" NUMERIC DEFAULT 0,
  "isBlocked" BOOLEAN DEFAULT false
);

-- ৩. মাস্টার অ্যাডমিন (Login: 01987624041 / 225588)
INSERT INTO users (id, name, phone, "password", "payPassword", role, balance)
VALUES ('admin_master', 'Master Admin', '01987624041', '225588', '225588', 'ADMIN', 999999);

-- ৪. ট্রানজেকশন টেবিল
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" TEXT REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'PENDING',
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  details TEXT,
  operator TEXT
);

-- ৫. অন্যান্য টেবিল
CREATE TABLE offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL,
  "regularPrice" NUMERIC,
  operator TEXT,
  validity TEXT,
  description TEXT
);

CREATE TABLE chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "senderId" TEXT NOT NULL,
  "recipientId" TEXT,
  text TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  "isAdmin" BOOLEAN DEFAULT false
);

CREATE TABLE app_settings (
  id INT PRIMARY KEY,
  "bkashNumber" TEXT DEFAULT '01XXXXXXXXX',
  "nagadNumber" TEXT DEFAULT '01XXXXXXXXX',
  "rocketNumber" TEXT DEFAULT '01XXXXXXXXX',
  banners TEXT[] DEFAULT ARRAY[]::TEXT[]
);

INSERT INTO app_settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- ৬. ক্যাশ রিফ্রেশ
NOTIFY pgrst, 'reload schema';`;

  const copySql = () => {
    navigator.clipboard.writeText(fullSqlReset);
    alert("সম্পূর্ণ রিসেট SQL কপি হয়েছে! সুপাবেজে রান করুন।");
  };

  const pendingTransactions = transactions.filter(t => t.status === 'PENDING');

  return (
    <div className="flex-1 flex flex-col bg-gray-50 overflow-hidden h-full">
      <header className="bg-white border-b p-4 flex justify-between items-center sticky top-0 z-10 shadow-sm">
        <div className="flex items-center space-x-2">
          <div className="w-8 h-8 bg-blue-900 rounded-lg flex items-center justify-center text-white">
            <Settings size={18} />
          </div>
          <h1 className="text-lg font-black text-gray-800 tracking-tight">অ্যাডমিন প্যানেল</h1>
        </div>
        <button onClick={onLogout} className="p-2 bg-red-50 text-red-500 rounded-xl active:scale-95 transition-all">
          <LogOut size={20} />
        </button>
      </header>

      <div className="bg-white flex border-b overflow-x-auto no-scrollbar scroll-smooth">
        {[
          { id: 'STATS', label: 'Stats', icon: <Smartphone size={14}/> },
          { id: 'REQUESTS', label: `Req (${pendingTransactions.length})`, icon: <Clock size={14}/> },
          { id: 'USERS', label: 'Users', icon: <Users size={14}/> },
          { id: 'OFFERS', label: 'Offers', icon: <Tag size={14}/> },
          { id: 'CHAT', label: 'Live Chat', icon: <Send size={14}/> },
          { id: 'DATABASE', label: 'Full Reset', icon: <Database size={14}/> },
          { id: 'SETTINGS', label: 'Settings', icon: <Settings size={14}/> },
        ].map((tab) => (
          <button 
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={`flex items-center space-x-2 whitespace-nowrap px-6 py-4 text-[10px] font-black uppercase tracking-widest transition-all ${activeTab === tab.id ? 'text-blue-900 border-b-4 border-blue-900 bg-blue-50/50' : 'text-gray-400 hover:text-gray-600'}`}
          >
            {tab.icon}
            <span>{tab.label}</span>
          </button>
        ))}
      </div>

      <div className="flex-1 overflow-y-auto pb-20 bg-gray-50/50">
        {activeTab === 'DATABASE' && (
          <div className="p-6">
             <div className="bg-white p-8 rounded-[40px] shadow-xl border border-blue-100">
                <div className="flex items-center space-x-4 mb-6">
                   <div className="w-14 h-14 bg-red-600 rounded-2xl flex items-center justify-center text-white shadow-lg">
                      <AlertTriangle size={30} />
                   </div>
                   <div>
                      <h3 className="text-xl font-black text-gray-800 tracking-tight">পুরোপুরি রিসেট (Full Fix)</h3>
                      <p className="text-gray-500 text-[10px] font-bold uppercase tracking-widest">Database Clean & Build</p>
                   </div>
                </div>

                <div className="bg-red-50 border-l-4 border-red-400 p-5 mb-8 rounded-r-2xl">
                   <p className="text-red-900 text-[11px] font-bold leading-relaxed">
                     আপনার সুপাবেজে <b>Table Missing</b> বা <b>Schema Cache</b> এরর দেখা দিলে নিচের কোডটি রান করুন। এটি সব টেবিল মুছে নতুন করে তৈরি করবে এবং মাস্টার অ্যাডমিন আইডি সেটআপ করবে।
                   </p>
                </div>
                
                <div className="bg-gray-900 p-6 rounded-3xl relative mb-8 group border-4 border-gray-800 shadow-inner overflow-hidden">
                   <pre className="max-h-60 overflow-y-auto no-scrollbar font-mono text-[9px] text-emerald-400 leading-relaxed">
                      {fullSqlReset}
                   </pre>
                   <div className="absolute top-4 right-4 bg-gray-800 p-2 rounded-xl text-white group-hover:bg-blue-600 transition-colors pointer-events-none">
                      <Copy size={16} />
                   </div>
                </div>

                <button 
                  onClick={copySql}
                  className="w-full bg-blue-900 text-white py-5 rounded-2xl font-black text-sm uppercase tracking-widest shadow-2xl flex items-center justify-center gap-3 active:scale-95 transition-all mb-4"
                >
                  <Copy size={20} /> সম্পূর্ণ Fix SQL কপি করুন
                </button>
             </div>
          </div>
        )}

        {activeTab === 'STATS' && (
          <div className="p-6 grid grid-cols-2 gap-4">
             <div className="bg-gradient-to-br from-blue-600 to-blue-800 p-6 rounded-[32px] text-white shadow-xl">
                <p className="text-[10px] font-bold opacity-70 uppercase mb-1">মোট ইউজার</p>
                <p className="text-3xl font-black">{users.length}</p>
             </div>
             <div className="bg-gradient-to-br from-orange-500 to-red-600 p-6 rounded-[32px] text-white shadow-xl">
                <p className="text-[10px] font-bold opacity-70 uppercase mb-1">পেন্ডিং অনুরোধ</p>
                <p className="text-3xl font-black">{pendingTransactions.length}</p>
             </div>
          </div>
        )}

        {activeTab === 'REQUESTS' && (
          <div className="p-4 space-y-4">
            {pendingTransactions.map(tx => (
              <div key={tx.id} className="bg-white p-6 rounded-[32px] border shadow-sm">
                <p className="text-xs font-black text-blue-900 uppercase mb-2">{tx.type}</p>
                <p className="text-2xl font-black text-gray-800">৳ {tx.amount}</p>
                <p className="text-[10px] text-gray-400 font-bold mb-4">{tx.details}</p>
                <div className="flex space-x-2">
                  <button onClick={() => onUpdateTransaction(tx.id, 'SUCCESS')} className="flex-1 bg-green-500 text-white py-3 rounded-xl font-bold text-xs uppercase">Approve</button>
                  <button onClick={() => onUpdateTransaction(tx.id, 'FAILED')} className="flex-1 bg-red-500 text-white py-3 rounded-xl font-bold text-xs uppercase">Reject</button>
                </div>
              </div>
            ))}
          </div>
        )}

        {activeTab === 'OFFERS' && (
          <div className="p-4 space-y-4">
             <button onClick={() => {
               const title = prompt("অফার টাইটেল:");
               const price = prompt("মূল্য:");
               const reg = prompt("রেগুলার মূল্য:");
               const type = prompt("টাইপ (REGULAR/DRIVE):") as any;
               const op = prompt("অপারেটর (gp/bl/robi/airtel/teletalk):");
               const val = prompt("মেয়াদ (যেমন: ৩০ দিন):");
               if (title && price && op) onManageOffers('ADD', { id: '', title, price: Number(price), regularPrice: Number(reg), type, operator: op, validity: val });
             }} className="w-full bg-blue-900 text-white py-4 rounded-2xl font-black text-xs uppercase flex items-center justify-center gap-2">
               <Plus size={18}/> নতুন অফার যোগ করুন
             </button>
             <div className="grid grid-cols-2 gap-3">
               {offers.map(offer => (
                 <div key={offer.id} className="bg-white p-4 rounded-2xl border shadow-sm relative">
                    <button onClick={() => onManageOffers('DELETE', offer)} className="absolute top-2 right-2 text-red-500"><Trash2 size={16}/></button>
                    <p className="text-[10px] font-black text-blue-900 uppercase">{offer.operator}</p>
                    <p className="text-xs font-black text-gray-800">{offer.title}</p>
                    <p className="text-lg font-black text-red-500">৳{offer.price}</p>
                 </div>
               ))}
             </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminDashboard;
